name: "Backend: Check the source code"
on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm i
        working-directory: ./backend
      - name: Run prettier
        run: npm run format
        working-directory: ./backend
      - name: Run eslint
        run: npm run lint
        working-directory: ./backend
      - name: Run build
        run: npm run build
        working-directory: ./backend
